-- Role: dan_ms_user
DROP ROLE IF EXISTS dan_ms_user;

CREATE ROLE dan_ms_user WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:j84PXhJmdITCjxELmLUMtg==$tO9EL3FlAyR5V5ElL8PRq2dtty2EpKSAbhPg2MxOhGU=:Yi9UViEDdijAxAUegQwKaOkgQuHspoqde5ppQw20RJ4=';